name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Construir imagen de la API
        run: docker build -f api/Containerfile -t taskflow-api:ci ./api

      - name: Construir imagen del worker
        run: docker build -f worker/Containerfile -t taskflow-worker:ci ./worker

      - name: Construir imagen del frontend
        run: docker build -f frontend/Containerfile -t taskflow-frontend:ci ./frontend

      - name: Escanear API con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: taskflow-api:ci
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Escanear worker con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: taskflow-worker:ci
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Escanear frontend con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: taskflow-frontend:ci
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Autenticarse en AWS vía OIDC
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::887540997584:role/github-actions-ecr-push
          aws-region: eu-central-1

      - name: Iniciar sesión en ECR
        if: github.event_name == 'push'
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 887540997584.dkr.ecr.eu-central-1.amazonaws.com

      - name: Etiquetar y subir imagen de la API a ECR
        if: github.event_name == 'push'
        run: |
          docker tag taskflow-api:ci 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-api:${{ github.sha }}
          docker tag taskflow-api:ci 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-api:latest
          docker push 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-api:${{ github.sha }}
          docker push 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-api:latest

      - name: Etiquetar y subir imagen del worker a ECR
        if: github.event_name == 'push'
        run: |
          docker tag taskflow-worker:ci 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-worker:${{ github.sha }}
          docker tag taskflow-worker:ci 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-worker:latest
          docker push 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-worker:${{ github.sha }}
          docker push 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-worker:latest

      - name: Etiquetar y subir imagen del frontend a ECR
        if: github.event_name == 'push'
        run: |
          docker tag taskflow-frontend:ci 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-frontend:${{ github.sha }}
          docker tag taskflow-frontend:ci 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-frontend:latest
          docker push 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-frontend:${{ github.sha }}
          docker push 887540997584.dkr.ecr.eu-central-1.amazonaws.com/taskflow-frontend:latest